name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      packages: write
    runs-on: "ubuntu-latest"
    outputs:
      imageName: fromJson(jobs.build.outputs.metadata)['image.name']
      digest: fromJson(jobs.build.outputs.metadata)['digest']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Use lowercase repository name as docker image name
        run: echo "DOCKER_IMAGE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ env.DOCKER_IMAGE_NAME }}:latest
  deploy-test:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "test"
      imageName: ${{ needs.build.outputs.imageName }}
      digest: ${{ needs.build.outputs.digest }}
  deploy-production:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "prod"
      imageName: ${{ needs.build.outputs.imageName }}
      digest: ${{ needs.build.outputs.digest }}
