on:
  push:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      #- run: echo "Hello world"
      #- run: go version

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ${{ github.repository }}:latest
