on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        type: environment
      imageid:
        description: 'Docker image'
        type: string
      digest:
        description: 'The SHA of the built image'
        type: string

  workflow_call:
    inputs:
      environment:
        description: 'Deployment environment'
        type: string
      imageid:
        description: 'Docker image'
        type: string
      digest:
        description: 'The SHA of the built image'
        type: string


jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    environment: ${{ inputs.environment }}
    steps:
      - run: |
          echo "Deploying docker image ${{ inputs.imageid }}@${{ inputs.digest }}"
          echo "Special variable: ${{ vars.WORKSHOP_ENV_VARIABLE }}"
