name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
      imageName:
        required: true
        type: string
      digest:
        required: true
        type: string
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      imageName:
        required: true
        type: string
      digest:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        run: "echo Deploying ${{ inputs.environment }} with image ${{ inputs.imageName }} and digest ${{ inputs.digest }}"
