# The "display name", shown in the GitHub UI
name: Test

# Trigger, run on push on any branch
on:
  pull_request:
  workflow_dispatch: # Triggers when a user manually requests a workflow to run

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/go-test.yml
    with:
      config-value: "Some value"
  lint:
    # Also add checkout and setup go steps here, like in previous tasks
    runs-on: ubuntu-latest

    steps:
      - name: Verify formatting
        run: |
          no_unformatted_files="$(gofmt -l $(git ls-files '*.go') | wc -l)"
          exit "$no_unformatted_files"
